services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: forestchurches
      MYSQL_USER: testUser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    container_name: dotnet-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=forestchurches;User=testUser;Password=mypassword;
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
