version: '3.8'

services:
  aspnetapp:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8080:8080"
    environment:
      - ConnectionStrings__DockerConfiguration=mysql://jack:Morgan155#1@mysql:3306/forestchurches
    networks:
      - app-network

  mysql:
    image: mysql:8.0-bookworm
    environment:
      MYSQL_ROOT_PASSWORD: Morgan155#1
      MYSQL_DATABASE: forestchurches
      MYSQL_USER: jack
      MYSQL_PASSWORD: Morgan155#1
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge